# Generated by Django 4.0.2 on 2022-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(null=True)),
                ('img', models.ImageField(default='KakaoTalk_Photo_2022-01-18-15-42-07.jpeg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mood', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('mood_pic', models.CharField(max_length=500)),
                ('detail_pic', models.CharField(max_length=500)),
                ('mood1', models.CharField(max_length=200, null=True)),
                ('mood2', models.CharField(max_length=200, null=True)),
                ('mood3', models.CharField(max_length=200, null=True)),
                ('minimal', models.IntegerField()),
                ('modern', models.IntegerField()),
                ('natural', models.IntegerField()),
                ('casual', models.IntegerField()),
                ('romantic', models.IntegerField()),
                ('individuality', models.IntegerField()),
                ('useful', models.IntegerField()),
                ('vintage', models.IntegerField()),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('ENFJ', models.FloatField()),
                ('ENFP', models.FloatField()),
                ('ENTJ', models.FloatField()),
                ('ENTP', models.FloatField()),
                ('ESFJ', models.FloatField()),
                ('ESFP', models.FloatField()),
                ('ESTJ', models.FloatField()),
                ('ESTP', models.FloatField()),
                ('INFJ', models.FloatField()),
                ('INFP', models.FloatField()),
                ('INTJ', models.FloatField()),
                ('INTP', models.FloatField()),
                ('ISFJ', models.FloatField()),
                ('ISFP', models.FloatField()),
                ('ISTJ', models.FloatField()),
                ('ISTP', models.FloatField()),
            ],
        ),
    ]
